run:
  timeout: 5m
severity:
  default-severity: warning
linters:
  enable:
    - asciicheck
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - funlen
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
