name: Pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: setup go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.3
      - name: run pre-commit checks
        uses: pre-commit/action@v3.0.1
