name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
      - name: setup go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.3
      - name: run tests
        run: make test
      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
